"""empty message

Revision ID: 51e30ca24bfd
Revises: 0ba725b08e06
Create Date: 2023-10-08 13:02:31.115268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e30ca24bfd'
down_revision = '0ba725b08e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyrobce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vyrobek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_group_id'], ['vyrobce.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vyrobek')
    op.drop_table('vyrobce')
    # ### end Alembic commands ###
